name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # If you have a build step, run it here
      # - name: Install deps
      #   run: npm ci
      # - name: Build
      #   run: npm run build

      - name: Deploy folder to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Frontend   # <-- change to your folder
